language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - python tests_main.py
matrix:
  include:
    - python: "2.7"
      install: pip install -r test-requirements.txt
